language: generic
sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: GHC=ghc-8.4 CC=gcc-7 CXX=g++-7
    - env: GHC=ghc-8.2 CC=gcc-7 CXX=g++-7
    - env: GHC=ghc-8.4 STACK=1 CC=gcc-7 CXX=g++-7
    - env: GHC=ghc-8.2 STACK=1 CC=gcc-7 CXX=g++-7

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - travis_retry curl -L https://www.haskell.org/cabal/release/cabal-install-2.2.0.0/cabal-install-2.2.0.0-x86_64-unknown-linux.tar.gz | tar xz  -C ~/.local/bin
    - eval export $(stack --compiler ${GHC} exec -- env | grep ^PATH=)
    - export TARGET_SUFF=$(if test -z "$STACK"; then printf ""; else printf -- "-stack"; fi)
    - env
    - ghc --version
    - $CXX --version
    - python3.6 --version
    - cabal update

script:
    - make build$TARGET_SUFF
    - make test$TARGET_SUFF
    - if [[ "$STACK:$GHC" = ":ghc-8.4" ]]; then make doc; fi

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - python3.6
      - socat
      - time
      - g++-7
      - libgmp-dev # for the sake of Haskell stack
      - acl
      - libacl1-dev

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: _build/doc/html/hsExprTest/
  on:
    branch: master
    condition: "$STACK:$GHC = :ghc-8.4"
