language: python
python:
  - 3.7
  - 3.8
  - 3.9
sudo: true
dist: bionic

before_install:
    - python3 --version
    - pip3 install aiohttp aiofiles pylibacl pyaml mypy

script:
    - make all

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

addons:
  apt:
    packages:
      - socat
      - curl
      - time
      - acl
      - libacl1-dev

# vim: expandtab
