upstream: http://127.0.0.1:8080/internal
interval: 10
courses:
    iv074:
        - path: /el/fi/podzim2019/IV074/ode/test/
          id: test
          notebook:
              name: "Test API odevzd치v치ren"
              short: test
              visible: True
              statistics: True
          attempts: 5
          aggregate: max
        - paths:
            - /el/fi/podzim2019/IV074/ode/ode_tests_1
            - /el/fi/podzim2019/IV074/ode/ode_tests_2
          id: test # Question ID for exprtest
          notebook:
              name: "Test API odevzd치v치ren 2"
              short: test2
              visible: True
              statistics: True
          attempts: null # null (for unlimited) or number of attempts
          # mail values:
          # - always
          # - never
          # - on_succes (all tests passed)
          # - on_failure (not all test passed)
          # - on_error (an error occured while evaluating)
          # it can be a list, e.g.: [on_error, on_failure]
          mail_student: never
          mail_teacher: [on_success, on_error, always]
          teachers: [xstill@fi.muni.cz]
          bcc: ib074-log@vstill.eu
          from: xstill@fi.muni.cz
          teachers_from_group: False # send to student's teacher based on seminar group
